# Используем официальный образ .NET
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CW/CW.csproj", "CW/"]
RUN dotnet restore "CW/CW.csproj"
COPY . .
WORKDIR "/src/CW"
RUN dotnet build "CW.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CW.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CW.dll"]
